### ISSUE TITLE
I get java.nio.file.FileAlreadyExistsException when I do init

### ISSUE THREAD

**Issue by bijan-eg** [advancedtelematic/ota-tuf#261]
When I want to initialize my repo on my mac I execute this command:
./garage-sign init --repo /repos/garageSign -c credentials.zip

Then I get this error:
java.nio.file.FileAlreadyExistsException: /repos/garageSign
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:94)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
	at java.base/sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:389)
	at java.base/java.nio.file.Files.createDirectory(Files.java:693)
	at com.advancedtelematic.tuf.cli.repo.TufRepo.$anonfun$initRepoDirs$1(TufRepo.scala:114)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at scala.util.Try$.apply(Try.scala:213)
	at com.advancedtelematic.tuf.cli.repo.TufRepo.initRepoDirs(TufRepo.scala:111)
	at com.advancedtelematic.tuf.cli.repo.ZipRepoInitialization$.init(RepoManagement.scala:158)
	at com.advancedtelematic.tuf.cli.repo.RepoManagement$.$anonfun$initialize$1(RepoManagement.scala:35)
	at scala.util.Success.flatMap(Try.scala:251)
	at com.advancedtelematic.tuf.cli.repo.RepoManagement$.initialize(RepoManagement.scala:34)
	at com.advancedtelematic.tuf.cli.CommandHandler$.handle(CommandHandler.scala:75)
	at com.advancedtelematic.tuf.cli.Cli$.$anonfun$buildCommandHandler$7(Cli.scala:601)
	at cats.Later.value$lzycompute(Eval.scala:150)
	at cats.Later.value(Eval.scala:149)
	at com.advancedtelematic.tuf.cli.Cli$.execute(Cli.scala:614)
	at com.advancedtelematic.tuf.cli.Cli$.delayedEndpoint$com$advancedtelematic$tuf$cli$Cli$1(Cli.scala:579)
	at com.advancedtelematic.tuf.cli.Cli$delayedInit$body.apply(Cli.scala:73)
	at scala.Function0.apply$mcV$sp(Function0.scala:39)
	at scala.Function0.apply$mcV$sp$(Function0.scala:39)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:17)
	at scala.App.$anonfun$main$1$adapted(App.scala:80)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at scala.App.main(App.scala:80)
	at scala.App.main$(App.scala:78)
	at com.advancedtelematic.tuf.cli.Cli$.main(Cli.scala:73)
	at com.advancedtelematic.tuf.cli.Cli.main(Cli.scala)

**Comment by simao** [comment]
Hi,
Can u do `garage-sign --version` Can you make sure the repo you are trying to init is empty?

IIRC that command is incomplete, you should be specifying the repo name and that name must not exist.

Cheers

**Comment by bijan-eg** [comment]
version: cli 0.7.2-48-gf606131

I did mention my repo name. It is "/repos/garageSign". but now I ran the command inside my /repo folder and it worked.

Thanks,

**Comment by simao** [comment]
Ah ok, my error. the repo name should not be a path, a simple name should be enough, though that should work.

thank you for your report.
